### ISSUE TITLE
[EPIC] Translate R code to Pandas

### ISSUE THREAD

**Issue by ns-rse** [sudlab/IsoSLAM#107]
There are a number of summarisations, statistical tests and plots made from the data that can be translated from the
current [R](https://www.r-project.org) to Python where the [Pandas](https://pandas.pydata.org),
[statsmodels](https://www.statsmodels.org) and [plotnine](https://plotnine.org/) packages provide equivalent
functionality to the Tidyverse, modelling language and ggplot2 used in the R code.

Each required function will be implemented as a module and an entry point will be added.

This epic serves to keep track of the various functions that need translating from the
[slam_3UIs](https://github.com/jjriley1/slam_3UIs/) repository.

- [ ] `gen_interaction_over_time_pvals.R`
- [ ] `get_over_time_pvalues.R`
- [ ] `get_over_time_pvalues_gene_level.R`
- [ ] `get_pair_halflives.R`
- [ ] `get_pair_pvalues.R`
- [ ] `get_pair_pvalues_all_events.R`
- [ ] `plot_conversions_per_pair.R`
- [ ] `plot_conversions_per_read.R`
- [ ] `summarize_counts.R`
