### ISSUE TITLE
[EPIC] Refactoring

### ISSUE THREAD

**Issue by ns-rse** [sudlab/IsoSLAM#64]
Epic to track the various aspects of refactoring that are required.

More tasks will be added as they are discovered and the code base is understood better by @ns-rse.

## Functions

- [x] #65
- [x] #66
- [x] #72
- [x] #73
- [x] `isoslam/io.py` Functions to load different file types...
  - [x] `bed` file using `cgatcore.iotools`
  - [x] `gtf` file using `cgatcore.iotools`
  - [x] `bam` file using [pysam](https://pypi.org/project/pysam/)
  - [x] `vcf` file using [pysam](https://pypi.org/project/pysam/)
- [x] #86
- [x] #87
- [x] #88
- [x] #89
- [x] #90
- [x] #91
- [x] #92
- [x] #93
- [x] #94
- [x] #95
- [x] #96
- [x] #144
- [x] #145
- [x] #147

## Style

As refactoring is undertaken we will use [pre-commit](https://pre-commit.com) hooks to ensure all files adhere to various linting styles.

- [x] Numpydoc docstrings
- [x] Lint with...
  - [x] Black (via Ruff)
  - [x] Flake8 (via Ruff)
  - [x] Ruff
  - [x] Pylint
  - [x] Mypy

**Comment by ns-rse** [comment]
Woohoo! Completed this refactoring.....EPIC! :tada:
